<b> NumPy Arrays Basics </b>

In [1]:
import numpy as np

In [2]:
# we used to create lists like
myList = [1,2,3,4,5]
type(myList)

list

In [10]:
# But now with numpy we create arrays (which is the main data structure of numpy)
# we can cast the above list to a numpy array
myArray = np.array(myList, dtype = float)

In [9]:
myArray

array([1., 2., 3., 4., 5.])

In [11]:
type(myArray)

numpy.ndarray

In [12]:
# we can also sepcify the minimum number of dimensions
myArray1 = np.array(myList, ndmin = 2)

In [13]:
myArray1

array([[1, 2, 3, 4, 5]])

In [14]:
# we can also generate an array using its own range function called "arange"
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# we can also provide a step as we do in range function
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

<b> Create an array of zeros with specified dimensions </b>

In [17]:
# "shape" is the tuple that provides the dimensions to the array 
np.zeros(shape = (2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [23]:
# order determines the shape is treated as [rows][columns] or [columns][rows]
np.zeros(shape = (3,2), dtype = int, order = 'C')

array([[0, 0],
       [0, 0],
       [0, 0]])

<b> We can also create array of ones with specified dimensions </b>

In [24]:
np.ones(shape = (3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

<b> Generate Random numbers using a seed value </b>

In [25]:
np.random.seed(101)

In [26]:
arr = np.random.randint(0, 100, 10)

In [27]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [28]:
arr = np.random.randint(0,100,10)

In [29]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [33]:
arr

array([ 0, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [35]:
# checks if all the elements evaluate to true
arr.all()

False

In [36]:
# index of maximum element along a given axis
arr.argmax()

8

In [38]:
# returns the sorted element indices
arr.argsort()

array([0, 6, 7, 2, 9, 3, 1, 5, 4, 8], dtype=int64)

In [39]:
arr.cumsum()

array([  0,  63, 103, 163, 255, 319, 324, 336, 429, 469], dtype=int32)

In [41]:
arr.max()

93

In [42]:
arr.min()

0

In [43]:
arr.mean()

46.9

In [46]:
arr[0] = 93

In [49]:
arr.argmax()

0

<b> We can also "Reshape" a given array </b>

In [50]:
arr

array([93, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [51]:
arr.shape

(10,)

In [56]:
arr.reshape((2,5))

array([[93, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [57]:
arr.reshape((5,2))

array([[93, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]])

<b> We can create matrices or 2D arrays directly while defining an array </b>

In [58]:
mat = np.arange(0,100).reshape((10,10))

In [59]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
# we can grap values using indexing
mat[5,3]

53

In [61]:
# we can use slicing to obtain a subset of the array or matrix
mat[:,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [62]:
mat[::2, ::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])