In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
# Spliting the data into dependent and independent variables
labels = data[:,4]
features = data[:,0:4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [7]:
# ML notations
X = features
y = labels

In [8]:
# Splitting the data into test and training set
# Also Randomizes the order of the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [9]:
# Feature scaling
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [12]:
Scaled_X_train = scaler.transform(X_train)
Scaled_X_test = scaler.transform(X_test)

In [13]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [14]:
# Initialize the ANN
classifier = Sequential()

In [15]:
classifier.add(Dense(4, input_dim = 4, activation = 'relu'))
classifier.add(Dense(8, activation = 'relu'))
classifier.add(Dense(1, activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
classifier.fit(Scaled_X_train, y_train, epochs = 100, verbose = 2)

Epoch 1/100
 - 0s - loss: 0.1136 - acc: 0.9717
Epoch 2/100
 - 0s - loss: 0.1098 - acc: 0.9728
Epoch 3/100
 - 0s - loss: 0.1063 - acc: 0.9739
Epoch 4/100
 - 0s - loss: 0.1028 - acc: 0.9761
Epoch 5/100
 - 0s - loss: 0.1010 - acc: 0.9706
Epoch 6/100
 - 0s - loss: 0.0972 - acc: 0.9750
Epoch 7/100
 - 0s - loss: 0.0946 - acc: 0.9739
Epoch 8/100
 - 0s - loss: 0.0922 - acc: 0.9728
Epoch 9/100
 - 0s - loss: 0.0905 - acc: 0.9739
Epoch 10/100
 - 0s - loss: 0.0878 - acc: 0.9771
Epoch 11/100
 - 0s - loss: 0.0865 - acc: 0.9750
Epoch 12/100
 - 0s - loss: 0.0832 - acc: 0.9782
Epoch 13/100
 - 0s - loss: 0.0822 - acc: 0.9761
Epoch 14/100
 - 0s - loss: 0.0786 - acc: 0.9804
Epoch 15/100
 - 0s - loss: 0.0770 - acc: 0.9826
Epoch 16/100
 - 0s - loss: 0.0755 - acc: 0.9782
Epoch 17/100
 - 0s - loss: 0.0744 - acc: 0.9782
Epoch 18/100
 - 0s - loss: 0.0733 - acc: 0.9804
Epoch 19/100
 - 0s - loss: 0.0713 - acc: 0.9793
Epoch 20/100
 - 0s - loss: 0.0695 - acc: 0.9815
Epoch 21/100
 - 0s - loss: 0.0680 - acc: 0.9804
E

In [21]:
y_pred = classifier.predict_classes(Scaled_X_test)

In [24]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
cm = confusion_matrix(y_test, y_pred)

In [26]:
cm

array([[256,   1],
       [  0, 196]], dtype=int64)

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       257
         1.0       0.99      1.00      1.00       196

   micro avg       1.00      1.00      1.00       453
   macro avg       1.00      1.00      1.00       453
weighted avg       1.00      1.00      1.00       453



In [28]:
# Saving the trained model
classifier.save('KerasMLModelTest.h5')

In [29]:
# Using the trained Model
from keras.models import load_model

In [30]:
MyKerasClassifier = load_model('KerasMLModelTest.h5')

In [32]:
y_pred = MyKerasClassifier.predict_classes(Scaled_X_test)

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       257
         1.0       0.99      1.00      1.00       196

   micro avg       1.00      1.00      1.00       453
   macro avg       1.00      1.00      1.00       453
weighted avg       1.00      1.00      1.00       453



In [38]:
len(y_pred[y_pred==0])

256